[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  CACHE_BUSTER = "$(date +%s)"

[[redirects]]
  from = "/api/*"
  to = "https://fight-companion.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
